2025-08-08 14:25:32,325 - INFO - Features={'MedInc': 8.3252, 'HouseAge': 41.0, 'AveRooms': 6.9841, 'AveBedrms': 1.0238, 'Population': 322.0, 'AveOccup': 2.5556, 'Latitude': 37.88, 'Longitude': -122.23} => Prediction=3.822
2025-08-08 14:32:57,753 - INFO - Features={'MedInc': 8.3252, 'HouseAge': 41.0, 'AveRooms': 6.9841, 'AveBedrms': 1.0238, 'Population': 322.0, 'AveOccup': 2.5556, 'Latitude': 37.88, 'Longitude': -122.23} => Prediction=3.822
2025-08-08 20:01:03,422 - ERROR - Failed to load model from MLflow
Traceback (most recent call last):
  File "C:\Users\Public\Documents\github\mlops-housing-pipeline\src\app.py", line 26, in <module>
    model = mlflow.sklearn.load_model(
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\sklearn\__init__.py", line 652, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\tracking\artifact_utils.py", line 115, in _download_artifact_from_uri
    repo = get_artifact_repository(artifact_uri=root_uri, tracking_uri=tracking_uri)
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 144, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri, tracking_uri)
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 82, in get_artifact_repository
    return repository(artifact_uri, tracking_uri=tracking_uri)
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\store\artifact\runs_artifact_repo.py", line 36, in __init__
    uri = RunsArtifactRepository.get_underlying_uri(artifact_uri, tracking_uri)
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\store\artifact\runs_artifact_repo.py", line 49, in get_underlying_uri
    uri = get_artifact_uri(
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\tracking\artifact_utils.py", line 53, in get_artifact_uri
    run = store.get_run(run_id)
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\store\tracking\file_store.py", line 741, in get_run
    run_info = self._get_run_info(run_id)
  File "C:\Users\HP-PC\AppData\Local\Programs\Python\Python310\lib\site-packages\mlflow\store\tracking\file_store.py", line 767, in _get_run_info
    raise MlflowException(
mlflow.exceptions.MlflowException: Run '73f83bfae79c4d56a240fa34998366ac' not found
